### ISSUE TITLE
cant launch

### ISSUE THREAD

**Issue by lvindotexe** [ill-inc/biomes-game#37]
cant run 
`./b data-snapshot run`

this is the error message i get
```
bazel run --config=release --show_result=0 --ui_event_filters=-INFO --color=yes --curses=yes //src:deploy_all_ts_deps -- /home/alvin/biomes-game/src/gen
Generating TypeScript dependencies (release)...
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "/home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125, column 33, in cc_autoconf_impl
                configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
        File "/home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 349, column 17, in configure_unix_toolchain
                cc = find_cc(repository_ctx, overriden_tools)
        File "/home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 314, column 23, in find_cc
                cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
        File "/home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 32, in _find_generic
                auto_configure_fail(msg)
        File "/home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: /DEFAULT.WORKSPACE.SUFFIX:520:13: fetching cc_autoconf rule //external:local_config_cc: Traceback (most recent call last):
        File "/home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125, column 33, in cc_autoconf_impl
                configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
        File "/home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 349, column 17, in configure_unix_toolchain
                cc = find_cc(repository_ctx, overriden_tools)
        File "/home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 314, column 23, in find_cc
                cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
        File "/home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 32, in _find_generic
                auto_configure_fail(msg)
        File "/home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: /home/alvin/.cache/bazel/_bazel_alvin/13276cfdaba77870b8cc7877d22bb8ca/external/bazel_tools/src/tools/launcher/BUILD:9:14: @bazel_tools//src/tools/launcher:launcher depends on @local_config_cc//:cc-compiler-k8 in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//':
Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: Analysis of target '//src:deploy_all_ts_deps' failed; build aborted:
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (3 packages loaded, 6 targets conf\
igured)
    currently loading: @crate_index// ... (2 packages)
    Fetching repository @pip_deps_docopt; Restarting. 4s
    Fetching https://files.pythonhosted.org/...uild-0.9.0-py3-none-any.whl; 4s
    Fetching https://crates.io/api/v1/crates/wasm-bindgen-cli/0.2.84/download
    Fetching https://github.com/.../cereal/archive/refs/tags/v1.3.2.tar.gz
    Fetching https://nodejs.org/dist/v18.12.0/node-v18.12.0-linux-x64.tar.xz
Error: There was an error while generating the TypeScript dependencies.
```
running on
windows/wsl2 ubuntu

**Comment by jeasinema** [comment]
Ran into this and got it solved by installing clang. Hope it works for you too!

**Comment by Ghewww** [comment]
I've also encountered the same issue, but it happened when running on a macOS system

**Comment by DevinLeamy** [comment]
Hi @Ghewww. Did installing `clang` solve your issue?

**Comment by turtlesoupy** [comment]
Closing as stale; believe this was a clang issue
