### ISSUE TITLE
Building wheel for voxeloo (setup.py) ... error

### ISSUE THREAD

**Issue by Junital** [ill-inc/biomes-game#58]
Environment: Windows WSL

When I run `./b data-snapshot run`, there is error in the part of building wheel for voxeloo.

Here are details:

```
ERROR: Command errored out with exit status 1:
   command: /mnt/e/Biomes/biomes-game-main/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1_g0d1rn/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1_g0d1rn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-t4vwgbv7
       cwd: /tmp/pip-req-build-1_g0d1rn/
  Complete output (42 lines):
  running bdist_wheel
  running build
  running build_ext
  2023/08/20 07:34:48 could not resolve the version 'latest' to an actual version number: unable to determine latest version: could not list Bazel versions in GCS bucket: could not list GCS objects at https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: could not fetch https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: Get "https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/": read tcp 172.31.20.236:50830->172.217.160.106:443: read: connection reset by peer
  Traceback (most recent call last):
    File "/tmp/pip-req-build-1_g0d1rn/setup.py", line 76, in run
      subprocess.check_output(["bazel", "--version"])
    File "/usr/local/lib/python3.9/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/local/lib/python3.9/subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['bazel', '--version']' returned non-zero exit status 1.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-1_g0d1rn/setup.py", line 152, in <module>
      setup(
    File "/mnt/e/Biomes/biomes-game-main/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/mnt/e/Biomes/biomes-game-main/.venv/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-1_g0d1rn/setup.py", line 81, in run
      raise RuntimeError(
  RuntimeError: There was a problem running Bazel, is it installed?
  ----------------------------------------
  ERROR: Failed building wheel for voxeloo
```

**Comment by bolshoytoster** [comment]
@Junital it looks like [this issue on the bazelisk repo](https://github.com/bazelbuild/bazelisk/issues/220) is related, it may help.

**Comment by DevinLeamy** [comment]
@Junital Have you install Bazel? 
```bash
npm install -g @bazel/bazelisk
```

**Comment by Junital** [comment]
@DevinLeamy Yes, but the error is not fixed.

**Comment by Junital** [comment]
@bolshoytoster That works, thank you.
