### ISSUE TITLE
Failed to create account

### ISSUE THREAD

**Issue by kakashiio** [ill-inc/biomes-game#60]
I have setup locally on my macOS (M1 Max & 64G) and started server successfully (The message "All servers are ready! You should be good to go! <3" appeared in the terminal).

But when I try to create account via emial, following error occured and the web page keep blank. How do I solve this issue?

[   web] 18:54:10 Fatal Error: Could not load gcloud config, have you installed the 'gcloud' CLI?
[   web] 18:54:10     at eval (webpack-internal:///./src/shared/logging.ts:135:18)
[   web] 18:54:10     at processContextError (webpack-internal:///./src/shared/logging.ts:144:7)
[   web] 18:54:10     at Function.fatal (webpack-internal:///./src/shared/logging.ts:203:30)
[   web] 18:54:10     at getGCloudConfig (webpack-internal:///./src/server/shared/google_adc.ts:40:62)
[   web] 18:54:10     at async getGCloudAccount (webpack-internal:///./src/server/shared/google_adc.ts:55:26)
[   web] 18:54:10     at async determineEmployeeUserId (webpack-internal:///./src/server/shared/bootstrap/sync.ts:37:21)
[   web] 18:54:10     at async safeDetermineEmployeeUserId (webpack-internal:///./src/server/shared/bootstrap/sync.ts:65:16)
[   web] 18:54:10     at async getServerSideProps (webpack-internal:///./src/pages/at/[...slug].tsx:387:34) 
[   web] 18:54:10 ALERT: Could not load gcloud config, have you installed the 'gcloud' CLI?
[   web] 18:54:10     at eval (webpack-internal:///./src/shared/logging.ts:135:18)
[   web] 18:54:10     at processContextError (webpack-internal:///./src/shared/logging.ts:144:7)
[   web] 18:54:10     at Function.fatal (webpack-internal:///./src/shared/logging.ts:203:30)
[   web] 18:54:10     at getGCloudConfig (webpack-internal:///./src/server/shared/google_adc.ts:40:62)
[   web] 18:54:10     at async getGCloudAccount (webpack-internal:///./src/server/shared/google_adc.ts:55:26)
[   web] 18:54:10     at async determineEmployeeUserId (webpack-internal:///./src/server/shared/bootstrap/sync.ts:37:21)
[   web] 18:54:10     at async safeDetermineEmployeeUserId (webpack-internal:///./src/server/shared/bootstrap/sync.ts:65:16)
[   web] 18:54:10     at async getServerSideProps (webpack-internal:///./src/pages/at/[...slug].tsx:387:34) pathname:/at
[   web] 18:54:10 About to exit with code: 1

**Comment by kakashiio** [comment]
I installed google-cloud-sdk and the issue solved.

MacOS
`brew install google-cloud-sdk`
