### ISSUE TITLE
Building Failed on Ubuntun 22.04

### ISSUE THREAD

**Issue by caesarchad** [ill-inc/biomes-game#61]
Comands:
    1  clang
    2  apt install clang
    3  sudo apt-get update
    4  sudo apt-get -y install clang
    5  clang -v
    6  python3 -v
    7  python3 -V
    8  nvm
    9  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
   10  nvm install v20
   11  nvm use v20
   12  sudo apt-get install git-lfs
   13  npm install -g @bazel/bazelisk
   14  git clone https://github.com/ill-inc/biomes-game.git
   15  git lfs pull
   16  ls
   17  cd biomes-game/
   18  git lfs pull
   19  python -m venv .venv
   20  python3 -m venv .venv
   21  apt install python3.10-venv
   22  python -m venv .venv
   23  python3 -m venv .venv
   24  source .venv/bin/activate
   25  pip install -r requirements.txt
   26  curl -s https://download.redis.io/releases/redis-7.0.8.tar.gz | tar xvz -C ${HOME}   && make -j`nproc` -C ${HOME}/redis-7.0.8   && sudo make install -C ${HOME}/redis-7.0.8   && rm -rf ${HOME}/redis-7.0.8
   27  ./b data-snapshot run
   28  npm install -g yarn
   29  ./b data-snapshot run
   30  history

Errors:
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: An error occurred during the fetch of repository 'python3_x86_64-unknown-linux-gnu':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/822d9986a8902a05a3176e66973f1adb/external/rules_python/python/repositories.bzl", line 194, column 25, in _python_repository_impl
                fail("The current user is root, please run as non-root when using the hermetic Python interpreter. See https://github.com/bazelbuild/rules_python/pull/713.")
Error in fail: The current user is root, please run as non-root when using the hermetic Python interpreter. See https://github.com/bazelbuild/rules_python/pull/713.
ERROR: /root/biomes-game/WORKSPACE.bazel:121:27: fetching python_repository rule //external:python3_x86_64-unknown-linux-gnu: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/822d9986a8902a05a3176e66973f1adb/external/rules_python/python/repositories.bzl", line 194, column 25, in _python_repository_impl
                fail("The current user is root, please run as non-root when using the hermetic Python interpreter. See https://github.com/bazelbuild/rules_python/pull/713.")
Error in fail: The current user is root, please run as non-root when using the hermetic Python interpreter. See https://github.com/bazelbuild/rules_python/pull/713.
ERROR: Error computing the main repository mapping: Encountered error while reading extension file 'requirements.bzl': no such package '@pip_deps//': no such package '@python3_x86_64-unknown-linux-gnu//': The current user is root, please run as non-root when using the hermetic Python interpreter. See https://github.com/bazelbuild/rules_python/pull/713.
Loading:
    Fetching repository @pip_deps; Restarting.
Error: There was an error while generating the TypeScript dependencies.
(.venv) root@biome-test-sg-2:~/biomes-game# history
![202308220445AM](https://github.com/ill-inc/biomes-game/assets/17776934/6f1ac9bc-0043-496e-9106-350e19d19b93)

**Comment by DevinLeamy** [comment]
Hi @caesarchad. Checkout https://stackoverflow.com/a/64093802. It seems that bazel may running into some problems with your host `python3`.
