### ISSUE TITLE
ImportError: dlopen(.../.venv/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_liq_attr_create'

### ISSUE THREAD

**Issue by natea** [ill-inc/biomes-game#70]
I'm seeing these PIL errors:

```
[   web] 18:26:44 INFO: Loaded WASM
[   web] 18:26:44 Traceback (most recent call last):
[   web] 18:26:44 Traceback (most recent call last):
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/build.py", line 23, in <module>
[   web] 18:26:44 Traceback (most recent call last):
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/build.py", line 23, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/build.py", line 23, in <module>
[   web] 18:26:44 Traceback (most recent call last):
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/build.py", line 23, in <module>
[   web] 18:26:44 Traceback (most recent call last):
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/build.py", line 23, in <module>
[   web] 18:26:44     import impl
[   web] 18:26:44     import impl
[   web] 18:26:44     import impl
[   web] 18:26:44     import impl
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/__init__.py", line 1, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/__init__.py", line 1, in <module>
[   web] 18:26:44     import impl
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/__init__.py", line 1, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/__init__.py", line 1, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/__init__.py", line 1, in <module>
[   web] 18:26:44 Traceback (most recent call last):
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/build.py", line 23, in <module>
[   web] 18:26:44 Traceback (most recent call last):
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/build.py", line 23, in <module>
[   web] 18:26:44     import impl
[   web] 18:26:44     import impl
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/__init__.py", line 1, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/__init__.py", line 1, in <module>
[   web] 18:26:44     from impl.materializers import materialize
[   web] 18:26:44     from impl.materializers import materialize
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/materializers.py", line 10, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/materializers.py", line 10, in <module>
[   web] 18:26:44     from impl.materializers import materialize
[   web] 18:26:44     from impl.materializers import materialize
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/materializers.py", line 10, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/materializers.py", line 10, in <module>
[   web] 18:26:44 Traceback (most recent call last):
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/build.py", line 23, in <module>
[   web] 18:26:44     from impl.materializers import materialize
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/materializers.py", line 10, in <module>
[   web] 18:26:44     from impl.materializers import materialize
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/materializers.py", line 10, in <module>
[   web] 18:26:44     from impl.materializers import materialize
[   web] 18:26:44 Traceback (most recent call last):
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/build.py", line 23, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/materializers.py", line 10, in <module>
[   web] 18:26:44     import impl
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/__init__.py", line 1, in <module>
[   web] 18:26:44     import impl
[   web] 18:26:44     from impl.materializers import materialize
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/__init__.py", line 1, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/materializers.py", line 10, in <module>
[   web] 18:26:44     from impl import (
[   web] 18:26:44     from impl import (
[   web] 18:26:44     from impl import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/blocks.py", line 12, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/blocks.py", line 12, in <module>
[   web] 18:26:44     from impl import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/blocks.py", line 12, in <module>
[   web] 18:26:44     from impl import (
[   web] 18:26:44     from impl import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/blocks.py", line 12, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/blocks.py", line 12, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/blocks.py", line 12, in <module>
[   web] 18:26:44     from impl.materializers import materialize
[   web] 18:26:44     from impl import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/blocks.py", line 12, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/materializers.py", line 10, in <module>
[   web] 18:26:44     from impl import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/blocks.py", line 12, in <module>
[   web] 18:26:44     from impl import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/blocks.py", line 12, in <module>
[   web] 18:26:44     from impl.textures import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/textures.py", line 9, in <module>
[   web] 18:26:44     from impl.textures import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/textures.py", line 9, in <module>
[   web] 18:26:44     from impl.textures import (
[   web] 18:26:44     from impl.textures import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/textures.py", line 9, in <module>
[   web] 18:26:44     from impl.textures import (
[   web] 18:26:44     from impl.textures import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/textures.py", line 9, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/textures.py", line 9, in <module>
[   web] 18:26:44     from impl.textures import (
[   web] 18:26:44     from impl.textures import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/textures.py", line 9, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/textures.py", line 9, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/textures.py", line 9, in <module>
[   web] 18:26:44     from impl.textures import (
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/src/galois/py/assets/impl/textures.py", line 9, in <module>
[   web] 18:26:44     from PIL import Image, ImageEnhance
[   web] 18:26:44     from PIL import Image, ImageEnhance
[   web] 18:26:44     from PIL import Image, ImageEnhance
[   web] 18:26:44     from PIL import Image, ImageEnhance
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/Image.py", line 89, in <module>
[   web] 18:26:44     from PIL import Image, ImageEnhance
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/Image.py", line 89, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/Image.py", line 89, in <module>
[   web] 18:26:44     from PIL import Image, ImageEnhance
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/Image.py", line 89, in <module>
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/Image.py", line 89, in <module>
[   web] 18:26:44     from PIL import Image, ImageEnhance
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/Image.py", line 89, in <module>
[   web] 18:26:44     from PIL import Image, ImageEnhance
[   web] 18:26:44     from PIL import Image, ImageEnhance
[   web] 18:26:44   File "/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/Image.py", line 89, in <module>
[   web] 18:26:45   File "/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/Image.py", line 89, in <module>
[   web] 18:26:45   File "/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/Image.py", line 89, in <module>
[   web] 18:26:45     from . import _imaging as core
[   web] 18:26:45     from . import _imaging as core
[   web] 18:26:45     from . import _imaging as core
[   web] 18:26:45 ImportError: dlopen(/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_liq_attr_create'
[   web] 18:26:45     from . import _imaging as core
[   web] 18:26:45 ImportError: dlopen(/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_liq_attr_create'
[   web] 18:26:45 ImportError: dlopen(/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_liq_attr_create'
[   web] 18:26:45 ImportError: dlopen(/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_liq_attr_create'
[   web] 18:26:45     from . import _imaging as core
[   web] 18:26:45     from . import _imaging as core
[   web] 18:26:45 ImportError: dlopen(/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_liq_attr_create'
[   web] 18:26:45 ImportError: dlopen(/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_liq_attr_create'
[   web] 18:26:45     from . import _imaging as core
[   web] 18:26:45 ImportError: dlopen(/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_liq_attr_create'
[   web] 18:26:45     from . import _imaging as core
[   web] 18:26:45     from . import _imaging as core
[   web] 18:26:45 ImportError: dlopen(/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_liq_attr_create'
[   web] 18:26:45 ImportError: dlopen(/Users/nateaune/Documents/code/biomes-game/.venv/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_liq_attr_create'
```

**Comment by DevinLeamy** [comment]
Looks like you're using `python3.11`. We use `python3.9` or `python3.10`. I suggest trying something like:
```bash
# Remove the existing .venv
rm -rf .venv
# After installing python3.10
python3.10 -m venv .venv
source .venv/bin/activate
# --ignore-installed: Ignore any site-packages that have been installed
pip install --ignore-installed -r requirements.txt
```

**Comment by turtlesoupy** [comment]
Closing as answered, happy to accept a python upgrade PR as we are quite out of date now.
