### ISSUE TITLE
Loading is unexpectedly stalled... Reloading may help

### ISSUE THREAD

**Issue by rayguo01** [ill-inc/biomes-game#80]
## \[Optional\] Relevant system information
- Operating system (e.g. Ubuntu 22.04) Ubuntu 22.04
- Browser (e.g. Firefox) ：Chrome

## What you did

Create Dev account，Access the http://localhost:3000/at

Loading Page show these words：Loading is unexpectedly stalled... [Reloading may help]
I have refreshed the page multiple times, and the result is the same. In the end, the same prompt appears.

So I replace texts from /biomes-game/src/galois/js/interface/gen/asset_versions.json
"wearables/animations": "asset_data/wearables/animations.ff71974b48582f4d7c3a33d7e9061bd9.glb"

Error Log:
Successfully installed voxeloo-0.2
Snapshot is already installed, nothing to do.
Asset not found: wearables/animations
Traceback (most recent call last):
  File "/data/biomes-game/./scripts/b/bootstrap.py", line 99, in <module>
    main()
  File "/data/biomes-game/./scripts/b/bootstrap.py", line 95, in main
    entrypoint()
  File "/data/biomes-game/scripts/b/b.py", line 1906, in entrypoint
    cli(prog_name="./b")
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/biomes-game/scripts/b/data_snapshot.py", line 299, in run
    ctx.invoke(check_for_missing_assets, error_on_missing=True)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/biomes-game/scripts/b/data_snapshot.py", line 388, in check_for_missing_assets
    raise Exception("Missing assets\nConsider running:\n$ git pull\n$ ./b data-snapshot uninstall\n$ ./b data-snapshot install\nto fetch the most up-to-date assets.")
Exception: Missing assets

===============================================
Then, I restored the modifications I made.

I disable the failing fetch in biomes-game/src/client/game/context_managers/map_manager.ts:
    try {
      this.isRequestingMetadata = true;
//      this.mapMetadata = await jsonFetch<WorldMapMetadataResponse>(
 //       "/api/world_map/metadata"
 //     );
      this.emitter.emit("onMapMetadataUpdated");
    } catch (error: any) {
      log.error("Error while requesting map metadata", { error });
    } finally {
      this.isRequestingMetadata = false;
      this.metadataTickThrottle.reset();
      this.eagerMetadataThrottle.reset();
    }

Then refresh the webpage,the url is change to http://localhost:3000/at/NewPlayerBRX9

but in the end，it still show these words：Loading is unexpectedly stalled... [Reloading may help]

 Log:
[  sync] 13:05:11   serverSessionId: WS85fQ6Mus5CvFn60I5Xyb
[  sync] 13:05:11   clientSessionId: kEp6xR8O2EbrmiIDSg3m
[  sync] 13:05:11 INFO: 3460649885801335:kEp6xR8O2EbrmiIDSg3m:WS85fQ6Mus5CvFn60I5Xyb: Disconnected. pathname:/sync/subscribe userId:3460649885801335
[  sync] 13:05:11 ws:
[  sync] 13:05:11   serverSessionId: WS85fQ6Mus5CvFn60I5Xyb
[  sync] 13:05:11   clientSessionId: kEp6xR8O2EbrmiIDSg3m
[   web] 13:05:11 INFO: 200 /_next/static/chunks/react-refresh.js?ts=1693659910171 pathname:/_next/static/chunks/react-refresh.js BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.002s
[  sync] 13:05:11 INFO: Deleting client: 3460649885801335
[   web] 13:05:12 INFO: 200 /_next/static/chunks/webpack.js?ts=1693659910171 pathname:/_next/static/chunks/webpack.js BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.002s
[   web] 13:05:12 INFO: 200 /_next/static/chunks/main.js?ts=1693659910171 pathname:/_next/static/chunks/main.js BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.001s
[   web] 13:05:12 INFO: 200 /_next/static/chunks/pages/_app.js?ts=1693659910171 pathname:/_next/static/chunks/pages/_app.js BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.004s
[   web] 13:05:12 INFO: 200 /_next/static/development/_ssgManifest.js?ts=1693659910171 pathname:/_next/static/development/_ssgManifest.js BDID:lBc5jL2keNwY0M29hJaz responseSize:76 latency:0.003s
[   web] 13:05:12 INFO: 200 /_next/static/development/_buildManifest.js?ts=1693659910171 pathname:/_next/static/development/_buildManifest.js BDID:lBc5jL2keNwY0M29hJaz responseSize:399 latency:0.002s
[   web] 13:05:12 INFO: 200 /_next/static/chunks/pages/at/%5B...slug%5D.js?ts=1693659910171 pathname:/_next/static/chunks/pages/at/%5B...slug%5D.js BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.006s
[   web] 13:05:13 INFO: 200 /_next/static/media/biomes-logo.50750b9b.png pathname:/_next/static/media/biomes-logo.50750b9b.png BDID:lBc5jL2keNwY0M29hJaz responseSize:590 latency:0.001s
[   web] 13:05:57 wait  - compiling /api/social/self_profile (client and server)...
[   web] 13:05:57 event - compiled successfully in 76 ms (368 modules)
[   web] 13:05:57 INFO: 200 /_next/static/chunks/src_gen_shared_cpp_ext_voxeloo-simd_wasm_js.js pathname:/_next/static/chunks/src_gen_shared_cpp_ext_voxeloo-simd_wasm_js.js BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.010s
[   web] 13:05:57 INFO: 304 /api/social/self_profile pathname:/api/social/self_profile userId:3460649885801335 BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.277s
[   web] 13:06:00 INFO: 200 /_next/static/media/wasm.bf215307.wasm pathname:/_next/static/media/wasm.bf215307.wasm BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.002s
[  sync] 13:06:02 INFO: 200 /sync BDID:lBc5jL2keNwY0M29hJaz authType:user clientSessionId:SeERoelYgHgvzrTfk1Lb serverSessionId:WSRDeOPzQ5ezlLPYMrKEBN checkUserId:3460649885801335 userId:3460649885801335
[  sync] 13:06:03 INFO: Creating client: 3460649885801335 pathname:/sync/createPlayer userId:3460649885801335 clientId:3460649885801335 gremlin:false
[  sync] 13:06:03 ws:
[  sync] 13:06:03   serverSessionId: WSRDeOPzQ5ezlLPYMrKEBN
[  sync] 13:06:03   clientSessionId: SeERoelYgHgvzrTfk1Lb
[  sync] 13:06:03 INFO: 3460649885801335:SeERoelYgHgvzrTfk1Lb:WSRDeOPzQ5ezlLPYMrKEBN: Starting sync. pathname:/sync/subscribe userId:3460649885801335
[  sync] 13:06:03 ws:
[  sync] 13:06:03   serverSessionId: WSRDeOPzQ5ezlLPYMrKEBN
[  sync] 13:06:03   clientSessionId: SeERoelYgHgvzrTfk1Lb
[  sync] 13:06:03 syncTarget:
[  sync] 13:06:03   kind:   localUser
[  sync] 13:06:03   userId: 3460649885801335
[  sync] 13:06:03 INFO: kind:   localUser
[  sync] 13:06:03 userId: 3460649885801335: Starting observer updates with 0 known entities pathname:/sync/subscribe userId:3460649885801335
[  sync] 13:06:03 ws:
[  sync] 13:06:03   serverSessionId: WSRDeOPzQ5ezlLPYMrKEBN
[  sync] 13:06:03   clientSessionId: SeERoelYgHgvzrTfk1Lb
[  sync] 13:06:04 INFO: 3460649885801335:SeERoelYgHgvzrTfk1Lb:WSRDeOPzQ5ezlLPYMrKEBN: Bootstrap complete, starting updates. pathname:/sync/subscribe userId:3460649885801335
[  sync] 13:06:04 ws:
[  sync] 13:06:04   serverSessionId: WSRDeOPzQ5ezlLPYMrKEBN
[  sync] 13:06:04   clientSessionId: SeERoelYgHgvzrTfk1Lb
[   web] 13:06:05 wait  - compiling /api/tweaks (client and server)...
[   web] 13:06:05 event - compiled successfully in 245 ms (210 modules)
[   web] 13:06:05 wait  - compiling /api/social/user_info_batch (client and server)...
[   web] 13:06:05 event - compiled successfully in 27 ms (230 modules)
[   web] 13:06:05 INFO: 304 /api/tweaks pathname:/api/tweaks userId:3460649885801335 BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.500s
[   web] 13:06:05 INFO: 304 /api/social/user_info_batch?ids=3460649885801335 pathname:/api/social/user_info_batch userId:3460649885801335 BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.414s
[   web] 13:06:06 wait  - compiling /api/cval_logging (client and server)...
[   web] 13:06:06 event - compiled successfully in 301 ms (232 modules)
[   web] 13:06:06 wait  - compiling /api/social/follow_list (client and server)...
[   web] 13:06:06 event - compiled successfully in 55 ms (233 modules)
[   web] 13:06:06 INFO: Logging cvals from source "startup" pathname:/api/cval_logging userId:3460649885801335
[   web] 13:06:06 INFO: 200 /api/cval_logging pathname:/api/cval_logging userId:3460649885801335 BDID:lBc5jL2keNwY0M29hJaz latency:0.449s
[   web] 13:06:06 INFO: 304 /api/social/follow_list?userId=3460649885801335&direction=outbound pathname:/api/social/follow_list userId:3460649885801335 BDID:lBc5jL2keNwY0M29hJaz responseSize:undefined latency:0.370s

**Comment by rayguo01** [comment]
More Log:

07c016b1cf6646f721866.webm BDID:YAnqVIOYHhPMofjyNttA responseSize:2862 latency:0.003s
[   web] 15:29:01 INFO: 404 /api/social/self_profile. Error
[   web] 15:29:01     at okOrAPIError (webpack-internal:///(api)/./src/server/web/errors.ts:76:15)
[   web] 15:29:01     at eval (webpack-internal:///(api)/./src/pages/api/social/self_profile.ts:34:69)
[   web] 15:29:01     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[   web] 15:29:01     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:148:26)
[   web] 15:29:01     at async eval (webpack-internal:///(api)/./src/server/web/errors.ts:68:13)
[   web] 15:29:01     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:71:9)
[   web] 15:29:01     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:55:13)
[   web] 15:29:01     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:52:9) pathname:/api/social/self_profile userId:1821285871798672 BDID:Gbffhlr3w3PFoSrzYvYy responseSize:undefined latency:0.006s
[   web] 15:29:01 error:
[   web] 15:29:01   code: not_found
[   web] 15:29:01 INFO: 200 /buckets/biomes-static/asset_data/audio/footstep-grass-3.4958ca6ec183d3bc40114c4b92035c87.webm pathname:/buckets/biomes-static/asset_data/audio/footstep-grass-3.4958ca6ec183d3bc40114c4b92035c87.webm BDID:YAnqVIOYHhPMofjyNttA responseSize:1950 latency:0.002s
[   web] 15:29:12 INFO: 404 /api/social/self_profile. Error
[   web] 15:29:12     at okOrAPIError (webpack-internal:///(api)/./src/server/web/errors.ts:76:15)
[   web] 15:29:12     at eval (webpack-internal:///(api)/./src/pages/api/social/self_profile.ts:34:69)
[   web] 15:29:12     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[   web] 15:29:12     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:148:26)
[   web] 15:29:12     at async eval (webpack-internal:///(api)/./src/server/web/errors.ts:68:13)
[   web] 15:29:12     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:71:9)
[   web] 15:29:12     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:55:13)
[   web] 15:29:12     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:52:9) pathname:/api/social/self_profile userId:1821285871798672 BDID:Gbffhlr3w3PFoSrzYvYy responseSize:undefined latency:0.013s
[   web] 15:29:12 error:
[   web] 15:29:12   code: not_found
[   web] 15:29:23 INFO: 404 /api/social/self_profile. Error
[   web] 15:29:23     at okOrAPIError (webpack-internal:///(api)/./src/server/web/errors.ts:76:15)
[   web] 15:29:23     at eval (webpack-internal:///(api)/./src/pages/api/social/self_profile.ts:34:69)
[   web] 15:29:23     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[   web] 15:29:23     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:148:26)
[   web] 15:29:23     at async eval (webpack-internal:///(api)/./src/server/web/errors.ts:68:13)
[   web] 15:29:23     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:71:9)
[   web] 15:29:23     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:55:13)
[   web] 15:29:23     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:52:9) pathname:/api/social/self_profile userId:1821285871798672 BDID:Gbffhlr3w3PFoSrzYvYy responseSize:undefined latency:0.009s
[   web] 15:29:23 error:
[   web] 15:29:23   code: not_found
[   web] 15:29:34 INFO: 404 /api/social/self_profile. Error
[   web] 15:29:34     at okOrAPIError (webpack-internal:///(api)/./src/server/web/errors.ts:76:15)
[   web] 15:29:34     at eval (webpack-internal:///(api)/./src/pages/api/social/self_profile.ts:34:69)
[   web] 15:29:34     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[   web] 15:29:34     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:148:26)
[   web] 15:29:34     at async eval (webpack-internal:///(api)/./src/server/web/errors.ts:68:13)
[   web] 15:29:34     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:71:9)
[   web] 15:29:34     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:55:13)
[   web] 15:29:34     at async eval (webpack-internal:///(api)/./src/server/web/util/api_middleware.ts:52:9) pathname:/api/social/self_profile userId:1821285871798672 BDID:Gbffhlr3w3PFoSrzYvYy responseSize:undefined latency:0.009s

**Comment by rayguo01** [comment]
The issue has been resolved. The host needs to open port 4700.

**Comment by turtlesoupy** [comment]
Great!
