### ISSUE TITLE
Can`t login and web server falls

### ISSUE THREAD

**Issue by BlayzerQ** [ill-inc/biomes-game#83]
When i click to "Login" or "Create account" web server falls and site falls

[bikkie] 20:57:38 INFO: Baking biscuits... priorTray:0 prior:0
[bikkie] 20:57:38 WARNING: Reading legacy tray id:4782339746648270
[bikkie] 20:57:38 ERROR: Error running pipeline batcher. AssertionError [ERR_ASSERTION]: Tray not found
[bikkie] 20:57:38     at Bakery.getTrayFromStorage (/home/biomes/biomes-game/src/server/shared/bikkie/bakery.ts:222:7)
[bikkie] 20:57:38     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[bikkie] 20:57:38     at async Bakery.legacyGetTray (/home/biomes/biomes-game/src/server/shared/bikkie/bakery.ts:240:18)
[bikkie] 20:57:38     at async Promise.all (index 0)
[bikkie] 20:57:38     at async Bakery.bakeTray (/home/biomes/biomes-game/src/server/shared/bikkie/bakery.ts:540:27)
[bikkie] 20:57:38     at async BikkieServer.doBake (/home/biomes/biomes-game/src/server/bikkie/server.ts:126:19)
[bikkie] 20:57:38     at async /home/biomes/biomes-game/src/shared/util/async.ts:746:9
[bikkie] 20:57:38 error:
[bikkie] 20:57:38   code:     ERR_ASSERTION
[bikkie] 20:57:38   actual:   false
[bikkie] 20:57:38   expected: true
[bikkie] 20:57:38   operator: ==
Terminated: web, exit code -9

**Comment by turtlesoupy** [comment]
This should be fixed on current `main` by the restored 2026-05-16 data snapshot. Please run:
git pull
./b data-snapshot uninstall
./b data-snapshot run

Quests also require the trigger server; that is covered by #98.
